version: '3.1' 
networks: 
  zbx-net: 
    driver: bridge 
services: 
  mysql: 
    container_name: mysql 
    image: mysql:5.7 
    networks: 
      - zbx-net 
    ports: 
      - '3306:3306' 
    volumes: 
      - './zabbix/mysql:/var/lib/data' 
    environment: 
      - MYSQL_ROOT_PASSWORD=zbxadm 
      - MYSQL_DATABASE=zabbix 
      - MYSQL_USER=zabbix 
      - MYSQL_PASSWORD=zbxadm 
  adminer: 
    image: adminer 
    restart: always 
    ports: 
      - 8082:8080 
  zabbix-server: 
    container_name: zabbix-server 
    image: zabbix/zabbix-server-mysql:ubuntu-5.0.1 
    networks: 
      - zbx-net 
    links: 
      - mysql 
    restart: always 
    ports: 
      - '10051:10051' 
    volumes: 
      - './zabbix/alertscripts:/usr/lib/zabbix/alertscripts' 
    environment: 
      - DB_SERVER_HOST=mysql 
      - MYSQL_DATABASE=zabbix 
      - MYSQL_USER=zabbix 
      - MYSQL_PASSWORD=zbxadm 
    depends_on: 
      - mysql 
  zabbix-frontend: 
    container_name: zabbix-frontend 
    image: zabbix/zabbix-web-apache-mysql:ubuntu-5.0.1 
    networks: 
      - zbx-net 
    links: 
      - mysql 
    restart: always 
    ports: 
      - '80:8080' 
      - '443:8443' 
    environment: 
      - DB_SERVER_HOST=mysql 
      - MYSQL_DATABASE=zabbix 
      - MYSQL_USER=zabbix 
      - MYSQL_PASSWORD=zbxadm 
      - PHP_TZ=America/Sao_Paulo 
    depends_on: 
      - mysql 
  grafana: 
    container_name: grafana 
    image: grafana/grafana 
    networks: 
      - zbx-net 
    links: 
      - mysql 
      - zabbix-server 
    restart: always 
    ports: 
      - '3000:3000' 
    environment: 
      - GF_INSTALL_PLUGINS=alexanderzobnin-zabbix-app 
    depends_on: 
      - mysql 
      - zabbix-server 
  zabbix-agent: 
    container_name: zabbix-agent 
    image: zabbix/zabbix-agent2:alpine-5.0.1 
    user: root 
    networks: 
      - zbx-net 
    links: 
      - zabbix-server 
    restart: always 
    privileged: true 
    volumes: 
      - /var/run:/var/run 
    ports: 
      - '10050:10050' 
    environment: 
      - ZBX_HOSTNAME=lab 
      - ZBX_SERVER_HOST=172.18.0.1
